name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20', '1.21' ]
    name: With Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test
        run: go test -race ./...
  static-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21' ]
    name: Static checks
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Go Vet
        run: go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: 'v1.55'
          args: $(rev=${{ env.REV }}; if [[ $rev != '' ]]; then echo --new-from-rev=$rev; fi)
      - name: Goimports
        run: |
          go run golang.org/x/tools/cmd/goimports@latest -w .
          git diff --quiet || (echo 'goimports requires code cleanup:' ; git diff ; exit 1)
      - name: Go Generate
        run: |
          go generate ./...
          # Bug in swag results in Flaky swagger docs - see https://github.com/swaggo/swag/issues/721
          # git diff --quiet  || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff ; exit 1)
          git diff --quiet -- . ":(exclude)docs" || (echo 'generated go files are not up to date, check go generate, go.sum and go.mod' ; git diff -- . ":(exclude)docs"; exit 1)
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21' ]
    name: Integration
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Generate GraphQL
        run: make generate-integrationtest-graphql
      - name: Test
        run: make integrationtest
